language: java
before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  - stage: 🚫 jdk.java.net - Archived OpenJDK General-Availability Releases
    env: JDK=11 🚫
    script: source ./install-jdk.sh --feature 11
